
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="asset/css/style.css">
    <title>Document</title>
</head>
<body>
<h2>FAST FOOD</h2>
<!-- <img src="../page/logo.png" alt="logo"> -->
<div class="container">
   
    
    
    <form action="" method="post">
        <fieldset>
            <legend>
                CONNEXION
            </legend>
            <label for="id_user">Identifiant</label>
            <input type="text" name="id_user" id="id_user"><br/> <br>
            <label for="pwd">Mot de pass</label>
            <input type="password" name="pwd" id="pwd"><br/> <br>
            <button type="submit" name="connexion">Connexion</button><br>
            <p>Vous n'avez pas encore de compte. Veuillez vous <a href="index.php?goto=user&target=store">Inscrire</a></p>
            <!-- <p>un compte administrateur <a href="index.php?goto=auth&target=login">admin</a></p> -->
        </fieldset>

    </form>

</div>   
</body>
</html>
