<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link rel="stylesheet" href="asset/css/style2.css">
</head>
<body>
    
<div class="container">
<h2>FAST FOOD</h2>


        <form action="" method="post">
            <fieldset>
                <legend>
                    FORMULAIRE D'INSCRIPTION
                </legend>
            <label for="fname"> Nom : </label>
            <input type="text" name="fname" id="fname" ><br>
            <label for="lname"> Prenom : </label>
            <input type="text" name="lname" id="lname"><br>
            <label for="id_user"> Identifiant : </label>
            <input type="text" name="id_user" id="id_user"><br>
            <label for="pwd"> Mot de pass : </label>
            <input type="password" name="pwd" id="pwd"><br>
            <label for="pwd"> Confirmer le mot de pass : </label>
            <input type="password" name="cpwd" id="cpwd"><br>
            <button type="submit">S'inscrire</button><br><br>
            </fieldset>

        </form>
      
    </div>
</body>
</html>
