<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="asset/css/style2.css">
    <title>menu</title>
</head>
<body>
    
</body>
</html>
<form action="" method="post">
    <fieldset>
        <legend>
            Ajout de menu
        </legend>
        <label for="menu">Nom du menu</label>
        <input type="text" name="menu" id="menu"><br><br>

        <!-- <label for="prix">Prix du menu</label>
        <input type="text" name="prix" id="prix"> -->

        <button type="submit">Enregistrer</button><br><br>
    </fieldset>
</form>