<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="asset/css/style.css">
    <title>Ajout de plats</title>
</head>
<body>
    
</body>
</html>

<form action="" method="post">
    <fieldset>
        <legend>
            Ajouter les plats
        </legend>
        <label for="plat">Nom du plat:</label>
        <input type="text" name="plats" id="plats"><br><br>

        <label for="prix">Prix du plat:</label>
        <input type="text" name="prix" id="prix"><br><br>

        <button type="submit">Enregistrer</button><br><br>
    </fieldset>
</form>